### PR TITLE
Add persistent file storage to solution using Azure Files

### LINKED ISSUE #24: App service restart removes all uploaded artifacts
### This issue is for a: 
```
- [X] bug report
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Hi, thanks for creating this, it is a great jumpstart! 
I've noticed an issue with the solution. The CTFd framework has a media library feature that allows you to place images on pages. The uploaded images are stored in the container filesystem. The problem occurs when you restart the website (app service), because when the container is restarted, all the files that were added are now gone. The same is true for attachments added to challenges. This results in broken CTFd website. 

### Minimal steps to reproduce
* Deploy this solution
* Login as admin
* Go to the admin panel
* Go to Pages and edit the exiting 'index' page
* Click the Media Libary button and add an image
* Add the image to the page using the editor
* Check that the image works.
* Optionally you can verify the image was added in the container, in the path `/opt/CTFd/CTFd/uploads/some-guid/filename`
* Restart the app service
* Notice the index page is now broken, because the image file no longer exists in the container. (An app service restart takes a few minutes, an initial refresh may serve a cached page, after full page reload it is broken). 

As an example, I replaced the logo in the index page with my own image and restarted the website. It is now a broken image:
image

### Any log messages given by the failure
N/A

### Expected/desired behavior
The website should continue to work after the app service is restarted.

### OS and Version?
N/A

### Versions
main branch

### Mention any other details that might be useful
CTFd allows configuration of the upload feature via the config.ini see: https://github.com/CTFd/CTFd/blob/master/CTFd/config.ini#L174
The default value is using the filesystem and path `/opt/CTFd/CTFd/uploads`, they also have AWS S3 bucket support.

I prefer to use Azure Files as persistent file storage because it would integrate better with this solution. I'll share my implementation with you via PR.

### PR DESCRIPTION
**Pull request by moerketh**
## Purpose
This PR adds persistent file storage to the solution via Azure Files. This is required to store files that persist across app service restarts. This includes images added via Media Library or challenge attachments that are uploaded to the CTFd website.

I've use the following article as guidance for the solution: https://learn.microsoft.com/en-us/azure/app-service/configure-connect-to-azure-storage

Fixes #24

## Does this introduce a breaking change?
```
[ ] Yes
[X] No
```

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Documentation content changes
[ ] Other... Please describe:
```

## How to Test
* Get the code in this branch
* Deploy to a resource group

## Test the code
Verify that the deployment succeeds without issue:
Screenshot 2024-07-20 184217

## What to Check
Verify that the app service now has an Azure Storage Mount correctly configured:
image

Verify that images uploaded via the CTFd Media Library are now stored on Azure Files:
image

Verify that images and attachments now persist across website restarts.

### CODE REVIEW

**Comment by balteravishay** [comment]
thanks contributing this @moerketh ! I will review this ASAP!

**Comment by moerketh** [comment]
I should have set the storageaccount public network access to 'Disabled'. Same as the Keyvault.
If you agree with this change in principle, I can update the code.

**Comment by balteravishay** [comment]
Yes I agree. Tyvm!

**Comment by moerketh** [comment]
I noticed the Keyvault is deployed after the webapp, allowing to use the website outbound IPs in the networkAcl. I can't do that for the storageAccount, because the website also needs a working mount of an existing fileshare. To remedy that, the storageAccount networkAcls are updated after the website is deployed.

Let me know if anything else needs attention.

**Comment by balteravishay** [comment]
thanks for your contribution @moerketh !

**Comment by balteravishay** [comment]
@moerketh could you please remove the arm.json file from the PR, it is autogenerated by the CI.

**Comment by moerketh** [comment]
@balteravishay sure, updated!

**Pull request merged**
